// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvApi.Migrations.SqliteMigrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20200715033820_Initial Creation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("Email");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Email = "Customer1@Email.com",
                            Name = "Customer1",
                            State = "Missouri"
                        },
                        new
                        {
                            Email = "Customer2@Email.com",
                            Name = "Customer2",
                            State = "Pennsylvania"
                        },
                        new
                        {
                            Email = "Customer3@Email.com",
                            Name = "Customer3",
                            State = "Colorado"
                        },
                        new
                        {
                            Email = "Customer4@Email.com",
                            Name = "Customer4",
                            State = "Kansas"
                        },
                        new
                        {
                            Email = "ghabergham0@cornell.edu",
                            Name = "Gussie Habergham",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "sdicks1@gov.uk",
                            Name = "Shea Dicks",
                            State = "Pennsylvania"
                        },
                        new
                        {
                            Email = "elehrian2@mediafire.com",
                            Name = "Eddy Lehrian",
                            State = "Oklahoma"
                        },
                        new
                        {
                            Email = "zneylan3@umich.edu",
                            Name = "Zachary Neylan",
                            State = "California"
                        },
                        new
                        {
                            Email = "lglasscoe4@ameblo.jp",
                            Name = "Leonora Glasscoe",
                            State = "Minnesota"
                        },
                        new
                        {
                            Email = "atripcony5@w3.org",
                            Name = "Alexina Tripcony",
                            State = "Virginia"
                        },
                        new
                        {
                            Email = "iheyburn6@exblog.jp",
                            Name = "Isidro Heyburn",
                            State = "Ohio"
                        },
                        new
                        {
                            Email = "tmacias7@twitpic.com",
                            Name = "Tod Macias",
                            State = "California"
                        },
                        new
                        {
                            Email = "nthamelt8@ycombinator.com",
                            Name = "Ninette Thamelt",
                            State = "Virginia"
                        },
                        new
                        {
                            Email = "lgilstin9@scribd.com",
                            Name = "Lesley Gilstin",
                            State = "Colorado"
                        },
                        new
                        {
                            Email = "ddhoogea@State.tx.us",
                            Name = "Demetrius D'Hooge",
                            State = "California"
                        },
                        new
                        {
                            Email = "dbennetb@twitpic.com",
                            Name = "Dorene Bennet",
                            State = "Wisconsin"
                        },
                        new
                        {
                            Email = "gportmanc@prweb.com",
                            Name = "Gertrud Portman",
                            State = "California"
                        },
                        new
                        {
                            Email = "gdauneyd@lulu.com",
                            Name = "Gay Dauney",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "hmcgarviee@ovh.net",
                            Name = "Hazel McGarvie",
                            State = "Arkansas"
                        },
                        new
                        {
                            Email = "vsahnowf@msn.com",
                            Name = "Viva Sahnow",
                            State = "New Mexico"
                        },
                        new
                        {
                            Email = "tlauchlang@apache.org",
                            Name = "Tobiah Lauchlan",
                            State = "New York"
                        },
                        new
                        {
                            Email = "evaillanth@so-net.ne.jp",
                            Name = "Erma Vaillant",
                            State = "California"
                        },
                        new
                        {
                            Email = "dgarrardi@ucla.edu",
                            Name = "Deonne Garrard",
                            State = "California"
                        },
                        new
                        {
                            Email = "sleipoldtj@meetup.com",
                            Name = "Stinky Leipoldt",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "jkillbeyk@yolasite.com",
                            Name = "Jillian Killbey",
                            State = "Ohio"
                        },
                        new
                        {
                            Email = "olayingl@eventbrite.com",
                            Name = "Orren Laying",
                            State = "New York"
                        },
                        new
                        {
                            Email = "rgianneschim@stumbleupon.com",
                            Name = "Rudiger Gianneschi",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "tmeasorn@godaddy.com",
                            Name = "Terrijo Measor",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "ddelahunto@blogger.com",
                            Name = "Dunstan Delahunt",
                            State = "Oklahoma"
                        },
                        new
                        {
                            Email = "bcoattsp@cisco.com",
                            Name = "Barclay Coatts",
                            State = "New York"
                        },
                        new
                        {
                            Email = "gwillattsq@shutterfly.com",
                            Name = "Gunar Willatts",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "ajaquinr@twitpic.com",
                            Name = "Anastasie Jaquin",
                            State = "Pennsylvania"
                        },
                        new
                        {
                            Email = "gjeffrays@amazon.co.uk",
                            Name = "Gisele Jeffray",
                            State = "Massachusetts"
                        },
                        new
                        {
                            Email = "nscedallt@howstuffworks.com",
                            Name = "Nickolas Scedall",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "echmielu@google.it",
                            Name = "Eve Chmiel",
                            State = "Michigan"
                        },
                        new
                        {
                            Email = "dmathiasenv@nhs.uk",
                            Name = "Douglass Mathiasen",
                            State = "New York"
                        },
                        new
                        {
                            Email = "ggergusw@opera.com",
                            Name = "Giovanna Gergus",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "jmilwardx@yelp.com",
                            Name = "Jedd Milward",
                            State = "New York"
                        },
                        new
                        {
                            Email = "mruckerty@wiley.com",
                            Name = "Mannie Ruckert",
                            State = "Oregon"
                        },
                        new
                        {
                            Email = "jgubbinsz@msn.com",
                            Name = "Jedd Gubbins",
                            State = "Alabama"
                        },
                        new
                        {
                            Email = "bfavey10@telegraph.co.uk",
                            Name = "Barbey Favey",
                            State = "Kentucky"
                        },
                        new
                        {
                            Email = "cbigmore11@omniture.com",
                            Name = "Connie Bigmore",
                            State = "District of Columbia"
                        },
                        new
                        {
                            Email = "mpatnelli12@vkontakte.ru",
                            Name = "Miranda Patnelli",
                            State = "Maryland"
                        },
                        new
                        {
                            Email = "tduce13@tinyurl.com",
                            Name = "Tallie Duce",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "asturdy14@taobao.com",
                            Name = "Angus Sturdy",
                            State = "Kansas"
                        },
                        new
                        {
                            Email = "mkennion15@java.com",
                            Name = "Menard Kennion",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "sbernardini16@reference.com",
                            Name = "Silvio Bernardini",
                            State = "Missouri"
                        },
                        new
                        {
                            Email = "bhazard17@typepad.com",
                            Name = "Burch Hazard",
                            State = "Illinois"
                        },
                        new
                        {
                            Email = "scowndley18@de.vu",
                            Name = "Skelly Cowndley",
                            State = "Pennsylvania"
                        },
                        new
                        {
                            Email = "avettore19@cbsnews.com",
                            Name = "Antonia Vettore",
                            State = "Kansas"
                        },
                        new
                        {
                            Email = "jquarry1a@pinterest.com",
                            Name = "Jinny Quarry",
                            State = "Iowa"
                        },
                        new
                        {
                            Email = "espottswood1b@ask.com",
                            Name = "Esdras Spottswood",
                            State = "California"
                        },
                        new
                        {
                            Email = "ewise1c@hao123.com",
                            Name = "Elora Wise",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "oburras1d@slate.com",
                            Name = "Orly Burras",
                            State = "Missouri"
                        },
                        new
                        {
                            Email = "bwinchcombe1e@flavors.me",
                            Name = "Berkie Winchcombe",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "hjansens1f@reverbnation.com",
                            Name = "Hussein Jansens",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "mpagden1g@symantec.com",
                            Name = "Mildred Pagden",
                            State = "District of Columbia"
                        },
                        new
                        {
                            Email = "csymper1h@mozilla.com",
                            Name = "Cyndia Symper",
                            State = "Illinois"
                        },
                        new
                        {
                            Email = "cofeeney1i@vkontakte.ru",
                            Name = "Cordell O'Feeney",
                            State = "Virginia"
                        },
                        new
                        {
                            Email = "cbuddington1j@indiegogo.com",
                            Name = "Cos Buddington",
                            State = "Indiana"
                        },
                        new
                        {
                            Email = "wsworn1k@dyndns.org",
                            Name = "Wilmer Sworn",
                            State = "District of Columbia"
                        },
                        new
                        {
                            Email = "nbriddock1l@mlb.com",
                            Name = "Nessie Briddock",
                            State = "New York"
                        },
                        new
                        {
                            Email = "dbanbrigge1m@ft.com",
                            Name = "Dela Banbrigge",
                            State = "California"
                        },
                        new
                        {
                            Email = "npicardo1n@hc360.com",
                            Name = "Nicoli Picardo",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "borbell1o@epa.gov",
                            Name = "Ban Orbell",
                            State = "New York"
                        },
                        new
                        {
                            Email = "vdeere1p@senate.gov",
                            Name = "Viva Deere",
                            State = "Virginia"
                        },
                        new
                        {
                            Email = "ncamps1q@apple.com",
                            Name = "Ninon Camps",
                            State = "Illinois"
                        },
                        new
                        {
                            Email = "knaisey1r@exblog.jp",
                            Name = "Katerine Naisey",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "cdhennin1s@scientificamerican.com",
                            Name = "Cybil Dhennin",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "areburn1t@theglobeandmail.com",
                            Name = "Adoree Reburn",
                            State = "New York"
                        },
                        new
                        {
                            Email = "cmckiddin1u@google.ca",
                            Name = "Casey McKiddin",
                            State = "Washington"
                        },
                        new
                        {
                            Email = "vcoping1v@jimdo.com",
                            Name = "Vance Coping",
                            State = "District of Columbia"
                        },
                        new
                        {
                            Email = "wpignon1w@woothemes.com",
                            Name = "Wilie Pignon",
                            State = "Iowa"
                        },
                        new
                        {
                            Email = "ssidry1x@hp.com",
                            Name = "Sheppard Sidry",
                            State = "Indiana"
                        },
                        new
                        {
                            Email = "cninnoli1y@google.com.br",
                            Name = "Corey Ninnoli",
                            State = "Minnesota"
                        },
                        new
                        {
                            Email = "jbignell1z@timesonline.co.uk",
                            Name = "Janel Bignell",
                            State = "Massachusetts"
                        },
                        new
                        {
                            Email = "kbeasleigh20@hao123.com",
                            Name = "Kori Beasleigh",
                            State = "Missouri"
                        },
                        new
                        {
                            Email = "gde21@japanpost.jp",
                            Name = "Gar De Andisie",
                            State = "Pennsylvania"
                        },
                        new
                        {
                            Email = "htarrant22@yahoo.co.jp",
                            Name = "Hermina Tarrant",
                            State = "Ohio"
                        },
                        new
                        {
                            Email = "jmaccoughen23@hud.gov",
                            Name = "Jaye MacCoughen",
                            State = "Massachusetts"
                        },
                        new
                        {
                            Email = "dtraylen24@spotify.com",
                            Name = "Dodi Traylen",
                            State = "Arkansas"
                        },
                        new
                        {
                            Email = "nflucker25@nasa.gov",
                            Name = "Natassia Flucker",
                            State = "California"
                        },
                        new
                        {
                            Email = "ivigne26@ehow.com",
                            Name = "Irwin Vigne",
                            State = "Connecticut"
                        },
                        new
                        {
                            Email = "fskim27@google.fr",
                            Name = "Franchot Skim",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "mkefford28@barnesandnoble.com",
                            Name = "Michaeline Kefford",
                            State = "Virginia"
                        },
                        new
                        {
                            Email = "rscouller29@salon.com",
                            Name = "Rosamond Scouller",
                            State = "California"
                        },
                        new
                        {
                            Email = "skrates2a@theatlantic.com",
                            Name = "Salome Krates",
                            State = "Ohio"
                        },
                        new
                        {
                            Email = "sleys2b@mozilla.org",
                            Name = "Scotti Leys",
                            State = "North Carolina"
                        },
                        new
                        {
                            Email = "ceatttok2c@hubpages.com",
                            Name = "Crosby Eatttok",
                            State = "New York"
                        },
                        new
                        {
                            Email = "rspratley2d@cdc.gov",
                            Name = "Ricky Spratley",
                            State = "Colorado"
                        },
                        new
                        {
                            Email = "ahandrik2e@sourceforge.net",
                            Name = "Alic Handrik",
                            State = "California"
                        },
                        new
                        {
                            Email = "osavil2f@lulu.com",
                            Name = "Olenolin Savil",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "kharrald2g@slate.com",
                            Name = "Kahaleel Harrald",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "tjoret2h@posterous.com",
                            Name = "Teddy Joret",
                            State = "Missouri"
                        },
                        new
                        {
                            Email = "rby2i@nih.gov",
                            Name = "Raddie By",
                            State = "Oklahoma"
                        },
                        new
                        {
                            Email = "ltampion2j@topsy.com",
                            Name = "Linn Tampion",
                            State = "Washington"
                        },
                        new
                        {
                            Email = "pincogna2k@acquirethisName.com",
                            Name = "Peggi Incogna",
                            State = "Texas"
                        },
                        new
                        {
                            Email = "bjaram2l@youku.com",
                            Name = "Bernadette Jaram",
                            State = "District of Columbia"
                        },
                        new
                        {
                            Email = "agatch2m@discovery.com",
                            Name = "Avictor Gatch",
                            State = "Florida"
                        },
                        new
                        {
                            Email = "agriswaite2n@goo.ne.jp",
                            Name = "Addy Griswaite",
                            State = "California"
                        },
                        new
                        {
                            Email = "lcurrier2o@goodreads.com",
                            Name = "Laird Currier",
                            State = "California"
                        },
                        new
                        {
                            Email = "ycattel2p@istockphoto.com",
                            Name = "Yevette Cattel",
                            State = "New York"
                        },
                        new
                        {
                            Email = "fhardiker2q@google.com.au",
                            Name = "Forest Hardiker",
                            State = "California"
                        },
                        new
                        {
                            Email = "fsheldrake2r@over-blog.com",
                            Name = "Forster Sheldrake",
                            State = "Georgia"
                        });
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Placed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerEmail");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "Customer1@Email.com",
                            Placed = new DateTime(2020, 1, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Open",
                            Total = 100m
                        },
                        new
                        {
                            Id = 2,
                            Completed = new DateTime(2020, 3, 3, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "Customer2@Email.com",
                            Placed = new DateTime(2020, 2, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Complete",
                            Total = 200m
                        });
                });

            modelBuilder.Entity("Entities.Server", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<bool>("IsOnLine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Name");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Name = "DEV-SrvrWeb",
                            IsOnLine = true
                        },
                        new
                        {
                            Name = "DEV-SrvrApp",
                            IsOnLine = true
                        },
                        new
                        {
                            Name = "DEV-SrvrRdb",
                            IsOnLine = true
                        },
                        new
                        {
                            Name = "QA-SrvrWeb",
                            IsOnLine = true
                        },
                        new
                        {
                            Name = "QA-SrvrApp",
                            IsOnLine = true
                        },
                        new
                        {
                            Name = "QA-SrvrRdb",
                            IsOnLine = true
                        },
                        new
                        {
                            Name = "PROD-SrvrWeb",
                            IsOnLine = false
                        },
                        new
                        {
                            Name = "PROD-SrvrApp",
                            IsOnLine = false
                        },
                        new
                        {
                            Name = "PROD-SrvrRdb",
                            IsOnLine = false
                        });
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.HasOne("Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
